name: Testing Docker image
on:
  push:
    branches:
      - master
      - develop
      - data_quality_check
  pull_request:
    branches:
      - master
      - develop
    tags:
      - v*
  workflow_dispatch:

jobs:
  docker_testing:
    runs-on: ubuntu-latest
    name: Running Docker testing
    steps:
      - name: Fetch source code
        uses: actions/checkout@v2
      - name: Create folders
        run: |
             mkdir ./inputs && chmod 777 ./inputs
             mkdir ./outputs && chmod 777 ./outputs
      - name: List folder contents
        run: |
             echo "Current folder" && ls -la
             echo "test_data" && ls -l ./test_data
      - name: Copy testing data files
        run: |
             cp "${PWD}/test_data"/* "${PWD}/inputs/"
             echo "inputs" && ls -l ./inputs
      - name: Folder contents
        run: |
             echo "Current folder" && ls -l
             echo "Inputs folder" && ls -l ./inputs
             echo "Outputs folder" && ls -l ./outputs
      - name: Build docker image
        run: docker build -t canopycover_test:latest ./
      - name: Compress docker image
        run: docker save canopycover_test:latest | gzip -7 -c - > canopycover_test_image.tar.gz
      - name: Upload docker image
        uses: actions/upload-artifact@v2
        with:
          name: canopycover_test_image
          path: canopycover_test_image.tar.gz
      - name: Run docker test
        run: docker run --rm -v "${PWD}/inputs:/inputs" -v "${PWD}/outputs:/outputs" canopycover_test:latest --working_space /outputs --metadata /inputs/meta.yaml /inputs/rgb_17_7_W.tif /inputs/mask_1.tif
      - name: Output folder contents
        run: echo "Outputs folder" && ls -l ./outputs
      - name: Check outputs
        run: |
             cat outputs/canopycover.csv
             chmod +x "./.github/workflows/docker_test_check_rgb.sh"
             "./.github/workflows/docker_test_check_rgb.sh"
      - name: Data quality check
        run: |
              curl -sfL https://raw.githubusercontent.com/aswinkarthik/csvdiff/master/install.sh | sh -s -- -b ./csvdiff
              echo "Showing differences - if any"
              ./csvdiff/csvdiff './test_data/canopycover.csv' './outputs/canopycover.csv' -columns 1 --primary-key 4 --format rowmark
              echo "Running check"
              if [[ "$(./csvdiff/csvdiff './test_data/canopycover.csv' './outputs/canopycover.csv' -columns 1 --primary-key 4 --format rowmark 2>&1 | grep -A 5 'Rows:' | wc -l  | tr -d '[:space:]')" == "1" ]]; then echo "Test canopy cover content matches expected"; exit 0; else echo "Error - canopy cover contents mismatch from test_data/canopycover.csv"; exit 1; fi;

  artifact_cleanup:
    runs-on: ubuntu-latest
    needs: [docker_testing]
    name: Cleanup artifacts upon success
    steps:
      - name: Remove docker artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: canopycover_test_image
